// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auhupuupxwxoxmcjxaxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1aHVwdXVweHd4b3htY2p4YXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjI0NDUsImV4cCI6MjA3MjE5ODQ0NX0.UHj0j8dAbTD6kRinKC7M2dk18hSbQehr6OXRT1uh1Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});